#Pour tout push dans le repo
# Déclencher le build d'une nouvelle image docker oe t'as capté quoi.!

name: build and push image
on: [push]
jobs:
  check-bats-version:
    runs-on: getting-started-latest
    steps:
      - uses: actions/checkout@v3
    
