#Pour tout push dans le repo
# Déclencher le build d'une nouvelle image docker oe t'as capté quoi.!

name: build and push image
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PWD }}
        
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.USERNAME }}/getting-started:latest
