#Pour tout push dans le repo
# Déclencher le build d'une nouvelle image docker oe t'as capté quoi.!

name: build and push image
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: Se connecter à Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ewen29242 }}
        password: ${{ secrets.Ouessant123!* }}
    - name: Construire et pousser l'image Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ewen29242/getting-started:latest
